import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/CommanComponets/Header";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <header>
            <Header />
          </header>
          {/* Main Section */}
          <main className="container min-h-screen mx-auto my-20">
            {children}
          </main>
          <Toaster richColors />

          {/* Footer */}
          <footer className="bg-blue-100 py-4 text-center">
            <p>Made In Love By coder jk...</p>
            <p>All Rights Reserved.</p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
